name: Deploy Laravel & Vue to Shared Hosting

# Memicu workflow setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout Kode
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Setup PHP & Cache Composer
      - name: 2. Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Langkah 3: Setup Node.js & Cache NPM
      - name: 3. Setup Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Langkah 4: Build Aplikasi
      - name: 4. Build Application Assets
        run: |
          composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
          npm install
          npm run build
          rm -rf .git .github node_modules

      # Langkah 5: Deploy ke Server
      - name: 5. Deploy to Server
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          echo "Starting deployment process..."
      - name: Backup .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: 'cp ${{ secrets.TARGET_DIR }}/.env ${{ secrets.TARGET_DIR }}/../.env.bak || true'
      - name: Deploy files with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          source: './'
          target: ${{ secrets.TARGET_DIR }}
          rm: true
          overwrite: true
          strip_components: 1
      - name: Restore .env & Finalize Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            echo "Restoring .env file..."
            mv ${{ secrets.TARGET_DIR }}/../.env.bak ${{ secrets.TARGET_DIR }}/.env || true
            cd ${{ secrets.TARGET_DIR }}
            echo "Running post-deployment commands..."
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize
            echo "Deployment finished successfully."
